name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.0

      - name: Install pipenv
        run: pip install pipenv
        
      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run pytest --cov --cov-fail-under=100
          pipenv run isort --recursive --diff
          pipenv run black --check .
          pipenv run flake8
          pipenv run mypy
